### ISSUE TITLE
Plugin no longer appears to be working

### ISSUE THREAD

**Issue by TheFiZi** [WangQiru/mercury_fulltext#12]
* ## _What_ is the issue?

The plugin no longer appears to be working with self-hosted with the Mercury API (mercury-parser-api). It worked immediately after deployment for a few weeks and stopped after the most recent update to mercury-parser-api or the update to this project from 7 days ago.

I'm not explicitly getting an error from either tool so I'm starting here for submitting a bug report.

* ## _What_ is your setup? (PHP version, database used, etc.)
CentOS 6
PHP 7.1.26
MariaDB 15.1

TTRSS 19.2 (900cdbb)
Node 10.15.1 (for mercury-parser-api)

* ## _Are_ there any error logs?

This is the output I'm seeing from mercury-parser-api. Not certain how to get any error logs from the plugin itself.

```
Serverless: GET /parser (λ: mercuryParser)

Serverless: Warning: handler 'mercuryParser' returned a promise and also uses a callback!
This is problematic and might cause issues in your lambda.
```

* ## _How_ can the issue be replicated?

Wait for a RSS feed I'm using `mercury_fulltext` with to post a new story, not see the content of that story, only the summary.

* ## Other Comments

Manually accessing the mercury-parser-api via: http://localhost:65518/parser?url=https://www.wired.com/story/zuckerberg-privacy-manifesto-questions/ appears to work properly with the correct content returned to the browser.

I get the same error when manually calling mercury-parser-api as the mercury_fulltext plugin appears to so that might be a red herring.

```
Serverless: GET /parser (λ: mercuryParser)

Serverless: Warning: handler 'mercuryParser' returned a promise and also uses a callback!
This is problematic and might cause issues in your lambda.
```

**Comment by HenryQW** [comment]
Hi, it appears you're using an outdated version of [API](https://github.com/HenryQW/mercury-parser-api). I've [rebuilt it](https://github.com/HenryQW/mercury-parser-api/commit/959ac4a07afb2b67a42c7dd01fb0a895bedc879a) from scratch, please try the latest version.

**Comment by TheFiZi** [comment]
So your rebuild requires docker and cannot be run standalone?

**Comment by HenryQW** [comment]
You can always run `node index.js` to start it locally without docker.

**Comment by TheFiZi** [comment]
Thank you

**Comment by TheFiZi** [comment]
Requesting this ticket be re-opened.

After deploying the newest version of the API it still does not appear to be working.

Here is the output from the API:

```
🚀Mercury Parser API listens on port 65518
GET /parser?url= 200 33 - 2.277 ms
```

This is the URL that was supposed to be passed to the API from the TT-RSS Plugin: `https://www.wired.com/story/you-may-have-forgotten-foursquare-it-didnt-forget-you`

If I manually do: `lynx localhost:65518/parser?url=https://www.wired.com/story/you-may-have-forgotten-foursquare-it-didnt-forget-you` I get the JSON output and this is the updated console output from the API:

```
🚀Mercury Parser API listens on port 65518
GET /parser?url= 200 33 - 2.277 ms
GET /parser?url=https://www.wired.com/story/you-may-have-forgotten-foursquare-it-didnt-forget-you 200 8701 - 375.868 ms
```
