### ISSUE TITLE
Plugin not re-writing article contents with returned information from API

### ISSUE THREAD

**Issue by TheFiZi** [WangQiru/mercury_fulltext#14]
* ## _What_ is the issue?

Plugin appears to be working up until re-writes the article content with the information returned from the mercury_api.

I can see the plugin passing the URL to the mercury_api but then the body of the articles is not being replaced with the returned results from the API.

* ## _What_ is your setup? (PHP version, database used, etc.)

CentOS 6
PHP 7.1.26
MariaDB 15.1

TTRSS 19.2 (900cdbb)
Node 10.15.1 (for mercury-parser-api)

Your mercury API

* ## _Are_ there any error logs?

None I can see. I can enable PHP debugging if that would be helpful and try to find something.

* ## _How_ can the issue be replicated?

Subscribe to a feed, enable the mercury_fulltext plugin, wait for feed to refresh with new articles.

I am testing with: https://www.wired.com/feed/category/business/latest/rss

* ## Other Comments

**Comment by HenryQW** [comment]
This is a bit weird, my ttrss is able to process fulltext for some articles, for exmaple:

https://www.wired.com/story/huawei-case-signals-new-us-china-cold-war-tech/

![image](https://user-images.githubusercontent.com/5896343/54160803-64bdb880-4448-11e9-8654-56ec3cf26a34.png)

https://www.wired.com/story/tim-wu-says-us-must-enforce-antitrust-laws/

![image](https://user-images.githubusercontent.com/5896343/54160817-6b4c3000-4448-11e9-93b6-3c85b0980842.png)

However, some articles aren't processed, such as:

https://www.wired.com/story/huawei-sues-us-prodding-prove-suspicions/

and 

https://www.wired.com/story/facebook-zuckerberg-privacy-pivot/


So I did a manual curl to my mercury api
```sh
curl mercury:3000/parser?url=https://www.wired.com/story/facebook-zuckerberg-privacy-pivot/
```

It returned errors:

```json
{"error":true,"messages":"The url parameter passed does not look like a valid URL. Please check your data and try again."}
```

But when I spinned up a local mercury api, it's able to return the content.

Please try a manual curl and let me know if you are experiencing the same problem.

**Comment by HenryQW** [comment]
I think I've found the issue, wired has a paywall which will prevent you from getting the article after you've read some.

![image](https://user-images.githubusercontent.com/5896343/54162562-c92f4680-444d-11e9-9496-86afc900b281.png)


This is when the local mercury api returned the very same error.

![image](https://user-images.githubusercontent.com/5896343/54162695-5d011280-444e-11e9-9406-54ecfb5ab2d2.png)


https://github.com/postlight/mercury-parser/blob/0940971069290b5bce4dc9422d8b4d0d20f7d3b5/dist/mercury.js#L362-L363


Unfortunately, there is nothing I can do about this.

**Comment by TheFiZi** [comment]
Of course! I completely forgot they had the limited amount of articles. When I was using the official API this was likely not a problem because it probably used a lot of public IPs.

Normally I wouldn't have this issue but because I'd removed/re-added a feed for testing it burned through all of my IPs views for 24 hours.

Thanks again for the assist.

Full disclosure: I have a sub to Wired.com but they don't offer full text RSS like Arstechnica does.
