### ISSUE TITLE
Doesn't seem to work with docker spun at AWS

### ISSUE THREAD

**Issue by zkvsky** [WangQiru/mercury_fulltext#16]
I have tt-rss ver. 19.2 at my vps, with mercury-api docker spun at AWS. I can access mercury parser via instance's public IP and can see it working, outpuput. ( eg. 10.14.15.17:3000/parser?url=yadayads ) but in tt-rss I can see that it's not being parsed at all, without any errors.

**Comment by HenryQW** [comment]
Very likely that means you have misconfigured your TTRSS, double check your settings for mercury plugin as well as your AWS firewall if any.

**Comment by zkvsky** [comment]
@HenryQW I'm not sure what I could've misconfigured, In plugin's options there's just ip:port eg. 15.47.1.124:3000.  Which is accessible and returns output via browser [ so I'm assuming it's not a firewall issue ].
Of course it's enabled per feed too.

Edit. It appears to be working for some sites, at least Polygon, I'll watch it more carefully and for a bit longer

**Comment by HenryQW** [comment]
It's been brilliant and stable for me since I came up with mercury-parser-api as the replacement. In some case there might be anti-crawling implementations to prevent bot-pattern requests, that's the only reason I can think of.

**Comment by zkvsky** [comment]
Yeah, I'm aware, in rare cases it can't pull anything while readability can. I'm comparing it to the output of a reader which uses legacy mercury api still. 
When it works it's a heaven.
I'm using AWS because my VPS is BSD based, so docker is no go
Is it advisable to have both readability and mercury plugins ON? I'm getting occasional deadlocks and I'm not sure what is causing that yet.
Thank you for your work, much appreciated.

**Comment by HenryQW** [comment]
I don’t think it’s a good idea to have both plugins enabled, because each article will be processed by all plugins sequentially, so the latter will override whatever result produced by the former.

**Comment by zkvsky** [comment]
They are never both enabled per feed though. It's always either Readability or Mercury not both of them. That's what I've meant.

**Comment by zkvsky** [comment]
I'm closing this since I've switched from AWS some time ago and can't remember if got it fixed or not.
