### ISSUE TITLE
Can't Enter API key

### ISSUE THREAD

**Issue by Wei-Xia** [WangQiru/mercury_fulltext#6]
Hey there, 

I added this plugin into plugins folder, and it showed up on localhost. However, I can't update with API key. (I could see **Get fulltext via Mercury Parser** in each sub)

Please see screenshots below for more details.

Do you have any idea how to solve this issue? Thanks!

![image](https://user-images.githubusercontent.com/9309906/38533947-7cc50922-3c49-11e8-9648-fa0da9a928f9.png)

![image](https://user-images.githubusercontent.com/9309906/38534006-c803e8ea-3c49-11e8-82b4-bf6a5ec67930.png)

**Comment by HenryQW** [comment]
Hi,

Unfortunately I couldn't reproduce the bug.

Please state your installation steps including OS distro, PHP version and database type.

**Comment by HenryQW** [comment]
Close due to inactivity.

**Comment by xdober** [comment]
@HenryQW Hi, I met the same question. I used two docker containers follow _https://github.com/clue/docker-ttrss_ . And the php version is 5.5.9, the  PostgreSQL version is 9.3.4.
When I try to open mercury_fulltext setting, there is no input just like the first picture @Wei-Xia attached. By checking the system log, I found this error, 
![snipaste_2018-06-15_16-17-33](https://user-images.githubusercontent.com/10195626/41457888-a4b22fc6-70b7-11e8-8e7b-5c13d5973bbd.png)
Do you have any idea how to solve this error? Thanks!

**Comment by HenryQW** [comment]
@xdober You are using an image that has been failing to build for 2 years, https://hub.docker.com/r/clue/ttrss/builds/, I wouldn't be surprised if you run into any error.

I think `print_hidden()` was introduced by ttrss in that period therefore your container doesn't have it.

Try to use a newer ttrss image. https://github.com/HenryQW/docker-ttrss-plugins

**Comment by xdober** [comment]
@HenryQW  Now it works. Thank you a lot!
