### ISSUE TITLE
Automatically active my feeds with this plugin and can't be unchecked

### ISSUE THREAD

**Issue by niegpie** [WangQiru/mercury_fulltext#7]
I may find a bug. You can try:
1. Add a new feed
2. Change the feed's name
3. mf plugin will be automatically enabled on that feed
4. mf plugin can't be disabled on that feed

**Comment by HenryQW** [comment]
Hi,

Unfortunately I couldn't reproduce the bug.

Please state your installation steps including OS distro, PHP version and database type.

**Comment by HenryQW** [comment]
Closed due to inactivity.
